services:
  mysql:
    image: mysql:8.0
    container_name: task_tracker_mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - task_tracker_net
  
  redis:
    image: redis:7-alpine
    container_name: task_tracker_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - task_tracker_net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_tracker_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      CONFIG_PATH: ./config/local.yaml
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - task_tracker_net

volumes:
  mysql_data:
  redis_data:

networks:
  task_tracker_net:
    driver: bridge