// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

type Cache_Expecter struct {
	mock *mock.Mock
}

func (_m *Cache) EXPECT() *Cache_Expecter {
	return &Cache_Expecter{mock: &_m.Mock}
}

// GetTeamTasks provides a mock function with given fields: ctx, teamID, dest
func (_m *Cache) GetTeamTasks(ctx context.Context, teamID int64, dest interface{}) (bool, error) {
	ret := _m.Called(ctx, teamID, dest)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamTasks")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, interface{}) (bool, error)); ok {
		return rf(ctx, teamID, dest)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, interface{}) bool); ok {
		r0 = rf(ctx, teamID, dest)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, interface{}) error); ok {
		r1 = rf(ctx, teamID, dest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Cache_GetTeamTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamTasks'
type Cache_GetTeamTasks_Call struct {
	*mock.Call
}

// GetTeamTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID int64
//   - dest interface{}
func (_e *Cache_Expecter) GetTeamTasks(ctx interface{}, teamID interface{}, dest interface{}) *Cache_GetTeamTasks_Call {
	return &Cache_GetTeamTasks_Call{Call: _e.mock.On("GetTeamTasks", ctx, teamID, dest)}
}

func (_c *Cache_GetTeamTasks_Call) Run(run func(ctx context.Context, teamID int64, dest interface{})) *Cache_GetTeamTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(interface{}))
	})
	return _c
}

func (_c *Cache_GetTeamTasks_Call) Return(_a0 bool, _a1 error) *Cache_GetTeamTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Cache_GetTeamTasks_Call) RunAndReturn(run func(context.Context, int64, interface{}) (bool, error)) *Cache_GetTeamTasks_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateCache provides a mock function with given fields: ctx, teamID
func (_m *Cache) InvalidateCache(ctx context.Context, teamID int64) error {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateCache")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, teamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Cache_InvalidateCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateCache'
type Cache_InvalidateCache_Call struct {
	*mock.Call
}

// InvalidateCache is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID int64
func (_e *Cache_Expecter) InvalidateCache(ctx interface{}, teamID interface{}) *Cache_InvalidateCache_Call {
	return &Cache_InvalidateCache_Call{Call: _e.mock.On("InvalidateCache", ctx, teamID)}
}

func (_c *Cache_InvalidateCache_Call) Run(run func(ctx context.Context, teamID int64)) *Cache_InvalidateCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Cache_InvalidateCache_Call) Return(_a0 error) *Cache_InvalidateCache_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Cache_InvalidateCache_Call) RunAndReturn(run func(context.Context, int64) error) *Cache_InvalidateCache_Call {
	_c.Call.Return(run)
	return _c
}

// SetTeamTasks provides a mock function with given fields: ctx, teamID, tasks
func (_m *Cache) SetTeamTasks(ctx context.Context, teamID int64, tasks interface{}) error {
	ret := _m.Called(ctx, teamID, tasks)

	if len(ret) == 0 {
		panic("no return value specified for SetTeamTasks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, interface{}) error); ok {
		r0 = rf(ctx, teamID, tasks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Cache_SetTeamTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTeamTasks'
type Cache_SetTeamTasks_Call struct {
	*mock.Call
}

// SetTeamTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID int64
//   - tasks interface{}
func (_e *Cache_Expecter) SetTeamTasks(ctx interface{}, teamID interface{}, tasks interface{}) *Cache_SetTeamTasks_Call {
	return &Cache_SetTeamTasks_Call{Call: _e.mock.On("SetTeamTasks", ctx, teamID, tasks)}
}

func (_c *Cache_SetTeamTasks_Call) Run(run func(ctx context.Context, teamID int64, tasks interface{})) *Cache_SetTeamTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(interface{}))
	})
	return _c
}

func (_c *Cache_SetTeamTasks_Call) Return(_a0 error) *Cache_SetTeamTasks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Cache_SetTeamTasks_Call) RunAndReturn(run func(context.Context, int64, interface{}) error) *Cache_SetTeamTasks_Call {
	_c.Call.Return(run)
	return _c
}

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cache {
	mock := &Cache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
