// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "task_tracker/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// GetTeamTasks provides a mock function with given fields: ctx, teamID
func (_m *Storage) GetTeamTasks(ctx context.Context, teamID int64) ([]domain.TaskResponse, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamTasks")
	}

	var r0 []domain.TaskResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]domain.TaskResponse, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []domain.TaskResponse); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_GetTeamTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamTasks'
type Storage_GetTeamTasks_Call struct {
	*mock.Call
}

// GetTeamTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID int64
func (_e *Storage_Expecter) GetTeamTasks(ctx interface{}, teamID interface{}) *Storage_GetTeamTasks_Call {
	return &Storage_GetTeamTasks_Call{Call: _e.mock.On("GetTeamTasks", ctx, teamID)}
}

func (_c *Storage_GetTeamTasks_Call) Run(run func(ctx context.Context, teamID int64)) *Storage_GetTeamTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Storage_GetTeamTasks_Call) Return(_a0 []domain.TaskResponse, _a1 error) *Storage_GetTeamTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_GetTeamTasks_Call) RunAndReturn(run func(context.Context, int64) ([]domain.TaskResponse, error)) *Storage_GetTeamTasks_Call {
	_c.Call.Return(run)
	return _c
}

// InsertTask provides a mock function with given fields: ctx, task
func (_m *Storage) InsertTask(ctx context.Context, task domain.TaskRequest) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for InsertTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TaskRequest) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_InsertTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertTask'
type Storage_InsertTask_Call struct {
	*mock.Call
}

// InsertTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task domain.TaskRequest
func (_e *Storage_Expecter) InsertTask(ctx interface{}, task interface{}) *Storage_InsertTask_Call {
	return &Storage_InsertTask_Call{Call: _e.mock.On("InsertTask", ctx, task)}
}

func (_c *Storage_InsertTask_Call) Run(run func(ctx context.Context, task domain.TaskRequest)) *Storage_InsertTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TaskRequest))
	})
	return _c
}

func (_c *Storage_InsertTask_Call) Return(_a0 error) *Storage_InsertTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_InsertTask_Call) RunAndReturn(run func(context.Context, domain.TaskRequest) error) *Storage_InsertTask_Call {
	_c.Call.Return(run)
	return _c
}

// SelectHistory provides a mock function with given fields: ctx, task_id
func (_m *Storage) SelectHistory(ctx context.Context, task_id int64) ([]domain.TaskHistory, error) {
	ret := _m.Called(ctx, task_id)

	if len(ret) == 0 {
		panic("no return value specified for SelectHistory")
	}

	var r0 []domain.TaskHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]domain.TaskHistory, error)); ok {
		return rf(ctx, task_id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []domain.TaskHistory); ok {
		r0 = rf(ctx, task_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TaskHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, task_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_SelectHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectHistory'
type Storage_SelectHistory_Call struct {
	*mock.Call
}

// SelectHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - task_id int64
func (_e *Storage_Expecter) SelectHistory(ctx interface{}, task_id interface{}) *Storage_SelectHistory_Call {
	return &Storage_SelectHistory_Call{Call: _e.mock.On("SelectHistory", ctx, task_id)}
}

func (_c *Storage_SelectHistory_Call) Run(run func(ctx context.Context, task_id int64)) *Storage_SelectHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Storage_SelectHistory_Call) Return(_a0 []domain.TaskHistory, _a1 error) *Storage_SelectHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_SelectHistory_Call) RunAndReturn(run func(context.Context, int64) ([]domain.TaskHistory, error)) *Storage_SelectHistory_Call {
	_c.Call.Return(run)
	return _c
}

// SelectTasks provides a mock function with given fields: ctx, filter
func (_m *Storage) SelectTasks(ctx context.Context, filter domain.TaskFilter) ([]domain.TaskResponse, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for SelectTasks")
	}

	var r0 []domain.TaskResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TaskFilter) ([]domain.TaskResponse, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TaskFilter) []domain.TaskResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TaskFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_SelectTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectTasks'
type Storage_SelectTasks_Call struct {
	*mock.Call
}

// SelectTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.TaskFilter
func (_e *Storage_Expecter) SelectTasks(ctx interface{}, filter interface{}) *Storage_SelectTasks_Call {
	return &Storage_SelectTasks_Call{Call: _e.mock.On("SelectTasks", ctx, filter)}
}

func (_c *Storage_SelectTasks_Call) Run(run func(ctx context.Context, filter domain.TaskFilter)) *Storage_SelectTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TaskFilter))
	})
	return _c
}

func (_c *Storage_SelectTasks_Call) Return(_a0 []domain.TaskResponse, _a1 error) *Storage_SelectTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_SelectTasks_Call) RunAndReturn(run func(context.Context, domain.TaskFilter) ([]domain.TaskResponse, error)) *Storage_SelectTasks_Call {
	_c.Call.Return(run)
	return _c
}

// TaskUpdate provides a mock function with given fields: ctx, update
func (_m *Storage) TaskUpdate(ctx context.Context, update domain.TaskUpdate) error {
	ret := _m.Called(ctx, update)

	if len(ret) == 0 {
		panic("no return value specified for TaskUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TaskUpdate) error); ok {
		r0 = rf(ctx, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_TaskUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TaskUpdate'
type Storage_TaskUpdate_Call struct {
	*mock.Call
}

// TaskUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - update domain.TaskUpdate
func (_e *Storage_Expecter) TaskUpdate(ctx interface{}, update interface{}) *Storage_TaskUpdate_Call {
	return &Storage_TaskUpdate_Call{Call: _e.mock.On("TaskUpdate", ctx, update)}
}

func (_c *Storage_TaskUpdate_Call) Run(run func(ctx context.Context, update domain.TaskUpdate)) *Storage_TaskUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TaskUpdate))
	})
	return _c
}

func (_c *Storage_TaskUpdate_Call) Return(_a0 error) *Storage_TaskUpdate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_TaskUpdate_Call) RunAndReturn(run func(context.Context, domain.TaskUpdate) error) *Storage_TaskUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
