// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "task_tracker/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// User is an autogenerated mock type for the User type
type User struct {
	mock.Mock
}

type User_Expecter struct {
	mock *mock.Mock
}

func (_m *User) EXPECT() *User_Expecter {
	return &User_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *User) CreateUser(ctx context.Context, user domain.UserRequest) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserRequest) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// User_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type User_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.UserRequest
func (_e *User_Expecter) CreateUser(ctx interface{}, user interface{}) *User_CreateUser_Call {
	return &User_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *User_CreateUser_Call) Run(run func(ctx context.Context, user domain.UserRequest)) *User_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserRequest))
	})
	return _c
}

func (_c *User_CreateUser_Call) Return(_a0 error) *User_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *User_CreateUser_Call) RunAndReturn(run func(context.Context, domain.UserRequest) error) *User_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, name
func (_m *User) GetUser(ctx context.Context, name string) (domain.UserResponse, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 domain.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.UserResponse, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.UserResponse); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(domain.UserResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// User_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type User_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *User_Expecter) GetUser(ctx interface{}, name interface{}) *User_GetUser_Call {
	return &User_GetUser_Call{Call: _e.mock.On("GetUser", ctx, name)}
}

func (_c *User_GetUser_Call) Run(run func(ctx context.Context, name string)) *User_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *User_GetUser_Call) Return(_a0 domain.UserResponse, _a1 error) *User_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *User_GetUser_Call) RunAndReturn(run func(context.Context, string) (domain.UserResponse, error)) *User_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewUser creates a new instance of User. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *User {
	mock := &User{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
