// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "task_tracker/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// AddUser provides a mock function with given fields: ctx, team_id, userID, owner
func (_m *Storage) AddUser(ctx context.Context, team_id int64, userID int64, owner int64) error {
	ret := _m.Called(ctx, team_id, userID, owner)

	if len(ret) == 0 {
		panic("no return value specified for AddUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64) error); ok {
		r0 = rf(ctx, team_id, userID, owner)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_AddUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUser'
type Storage_AddUser_Call struct {
	*mock.Call
}

// AddUser is a helper method to define mock.On call
//   - ctx context.Context
//   - team_id int64
//   - userID int64
//   - owner int64
func (_e *Storage_Expecter) AddUser(ctx interface{}, team_id interface{}, userID interface{}, owner interface{}) *Storage_AddUser_Call {
	return &Storage_AddUser_Call{Call: _e.mock.On("AddUser", ctx, team_id, userID, owner)}
}

func (_c *Storage_AddUser_Call) Run(run func(ctx context.Context, team_id int64, userID int64, owner int64)) *Storage_AddUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(int64))
	})
	return _c
}

func (_c *Storage_AddUser_Call) Return(_a0 error) *Storage_AddUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_AddUser_Call) RunAndReturn(run func(context.Context, int64, int64, int64) error) *Storage_AddUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTeam provides a mock function with given fields: ctx, name, owner
func (_m *Storage) CreateTeam(ctx context.Context, name string, owner int64) error {
	ret := _m.Called(ctx, name, owner)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, name, owner)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_CreateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeam'
type Storage_CreateTeam_Call struct {
	*mock.Call
}

// CreateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - owner int64
func (_e *Storage_Expecter) CreateTeam(ctx interface{}, name interface{}, owner interface{}) *Storage_CreateTeam_Call {
	return &Storage_CreateTeam_Call{Call: _e.mock.On("CreateTeam", ctx, name, owner)}
}

func (_c *Storage_CreateTeam_Call) Run(run func(ctx context.Context, name string, owner int64)) *Storage_CreateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *Storage_CreateTeam_Call) Return(_a0 error) *Storage_CreateTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_CreateTeam_Call) RunAndReturn(run func(context.Context, string, int64) error) *Storage_CreateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeams provides a mock function with given fields: ctx, userID
func (_m *Storage) GetTeams(ctx context.Context, userID int64) ([]domain.TeamResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeams")
	}

	var r0 []domain.TeamResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]domain.TeamResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []domain.TeamResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TeamResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_GetTeams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeams'
type Storage_GetTeams_Call struct {
	*mock.Call
}

// GetTeams is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *Storage_Expecter) GetTeams(ctx interface{}, userID interface{}) *Storage_GetTeams_Call {
	return &Storage_GetTeams_Call{Call: _e.mock.On("GetTeams", ctx, userID)}
}

func (_c *Storage_GetTeams_Call) Run(run func(ctx context.Context, userID int64)) *Storage_GetTeams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Storage_GetTeams_Call) Return(_a0 []domain.TeamResponse, _a1 error) *Storage_GetTeams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_GetTeams_Call) RunAndReturn(run func(context.Context, int64) ([]domain.TeamResponse, error)) *Storage_GetTeams_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamsInfo provides a mock function with given fields: ctx
func (_m *Storage) GetTeamsInfo(ctx context.Context) ([]domain.TeamInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamsInfo")
	}

	var r0 []domain.TeamInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.TeamInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.TeamInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TeamInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_GetTeamsInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamsInfo'
type Storage_GetTeamsInfo_Call struct {
	*mock.Call
}

// GetTeamsInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Storage_Expecter) GetTeamsInfo(ctx interface{}) *Storage_GetTeamsInfo_Call {
	return &Storage_GetTeamsInfo_Call{Call: _e.mock.On("GetTeamsInfo", ctx)}
}

func (_c *Storage_GetTeamsInfo_Call) Run(run func(ctx context.Context)) *Storage_GetTeamsInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Storage_GetTeamsInfo_Call) Return(_a0 []domain.TeamInfo, _a1 error) *Storage_GetTeamsInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_GetTeamsInfo_Call) RunAndReturn(run func(context.Context) ([]domain.TeamInfo, error)) *Storage_GetTeamsInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NotInTeam provides a mock function with given fields: ctx
func (_m *Storage) NotInTeam(ctx context.Context) ([]domain.NotInTeam, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NotInTeam")
	}

	var r0 []domain.NotInTeam
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.NotInTeam, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.NotInTeam); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.NotInTeam)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_NotInTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotInTeam'
type Storage_NotInTeam_Call struct {
	*mock.Call
}

// NotInTeam is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Storage_Expecter) NotInTeam(ctx interface{}) *Storage_NotInTeam_Call {
	return &Storage_NotInTeam_Call{Call: _e.mock.On("NotInTeam", ctx)}
}

func (_c *Storage_NotInTeam_Call) Run(run func(ctx context.Context)) *Storage_NotInTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Storage_NotInTeam_Call) Return(_a0 []domain.NotInTeam, _a1 error) *Storage_NotInTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_NotInTeam_Call) RunAndReturn(run func(context.Context) ([]domain.NotInTeam, error)) *Storage_NotInTeam_Call {
	_c.Call.Return(run)
	return _c
}

// TopUsers provides a mock function with given fields: ctx
func (_m *Storage) TopUsers(ctx context.Context) ([]domain.TopUsers, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TopUsers")
	}

	var r0 []domain.TopUsers
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.TopUsers, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.TopUsers); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TopUsers)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_TopUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TopUsers'
type Storage_TopUsers_Call struct {
	*mock.Call
}

// TopUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Storage_Expecter) TopUsers(ctx interface{}) *Storage_TopUsers_Call {
	return &Storage_TopUsers_Call{Call: _e.mock.On("TopUsers", ctx)}
}

func (_c *Storage_TopUsers_Call) Run(run func(ctx context.Context)) *Storage_TopUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Storage_TopUsers_Call) Return(_a0 []domain.TopUsers, _a1 error) *Storage_TopUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_TopUsers_Call) RunAndReturn(run func(context.Context) ([]domain.TopUsers, error)) *Storage_TopUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
